---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Add a non-root user to test nvm
      user:
        name: nvm_tester
        comment: Nvm Tester

    - name: Add some modules for testing (Debian)
      apt: name=sudo state=present
      when: ansible_os_family == "Debian"

    - name: Add some modules for testing (RedHat)
      yum: name=sudo state=present
      when: ansible_os_family == "RedHat"

  roles:
    - role: ansible-nvm-node
      nvm_node_version: "8.11.3"
